Completed User endpoints
Devsoc-BPGC/bits-stack-backend pull request #26
Opened 2021-03-26 14:44 UTC by ritvij14

## Pull request checklist

Please check if your PR :rocket: fulfills the following requirements:
- [x] Build (`npm run start`) was run locally and new changes were working correctly
- [x] Lint (`npm run linter`) has passed locally and any fixes were made for failures

## Pull request type

 

Please check the type of change your PR introduces:
- [x] Feature

Fixes #20 

## What is the new behavior?

Screenshots of Postman results and database:-
### Create user
![WhatsApp Image 2021-03-26 at 6 21 10 PM](https://user-images.githubusercontent.com/51456744/112648420-86dbd500-8e6f-11eb-9021-212b08d1941f.jpeg)
![WhatsApp Image 2021-03-26 at 6 30 39 PM](https://user-images.githubusercontent.com/51456744/112648426-880d0200-8e6f-11eb-956a-c97d6c53870e.jpeg)

### Get user (by id)
![image](https://user-images.githubusercontent.com/51456744/112648567-ab37b180-8e6f-11eb-9ca4-4c879742f42c.png)

### Update user
![image](https://user-images.githubusercontent.com/51456744/112648800-e2a65e00-8e6f-11eb-8bf6-b76145406072.png)
![image](https://user-images.githubusercontent.com/51456744/112648687-c1de0880-8e6f-11eb-87e3-442b43da9798.png)
![image](https://user-images.githubusercontent.com/51456744/112648771-d7ebc900-8e6f-11eb-8de6-000b30de1651.png)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2021-03-26 15:59 UTC, Sarvesh67 requested changes

2021-03-26 15:59 UTC, Sarvesh67 commented on src/modules/User/user.service.ts
> +	async createUser(user: CreateUserDto): Promise<Users> {
Don't use DTO here, use it only in the controller and convert the input into Users object in the controller itself.

2021-03-27 06:14 UTC, ritvij14 commented on src/modules/User/user.service.ts
> +	async createUser(user: CreateUserDto): Promise<Users> {
Done

2021-03-27 16:16 UTC, Sarvesh67 requested changes
- Do not use error handling in the controller itself. Apply exception filters at either the controller level or the handler level depending on its relevance.
 - Add a delete user api too.

2021-03-30 15:00 UTC, Sarvesh67 requested changes

2021-03-30 15:00 UTC, Sarvesh67 commented on src/modules/User/user.service.ts
> +	async updateUser(userID: number, user: Users): Promise<Users | undefined> {
Remove findById method calls. Just use the response of update method.

2021-03-30 16:38 UTC, merged